name: Hola Mundo

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Hola mundo-Soy Eduardo Dominguez Librado"
        
      - name: Touch file
        run: |
          touch hola.txt
          ls -al
          
      - name: Set text
        run: |
          echo "Hola mundo nuevo" >> hola.txt
          ls -al
          
      - name: Read file
        run: |
          cat hola.txt

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Directorio
        run: ls -al
